#!/bin/bash

#SBATCH --job-name=Alignment_summary_metrics
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32G
#SBATCH --array=1-4
#SBATCH --output=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/logs/AlignmentMetrics_Insertsize_Dog_%A_%a.out
#SBATCH --error=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/logs/AlignmentMetrics_InsertSize_Dog_%A_%a.err
#SBATCH --chdir=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/output/bam_output

module purge

# Carga tus modulos en la siguiente linea

module load picard/2.6.0

# Your script goes here

Dog_ID="P${SLURM_ARRAY_TASK_ID}"

echo "Procesando la muestra ${Dog_ID} en la tarea ${SLURM_ARRAY_TASK_ID}" 

picard CollectAlignmentSummaryMetrics \
R=/mnt/data/cgonzaga/Data/Dog_genomes/reference/canFam6.fa.gz \
I=${Dog_ID}.alignment.sort.dedup.bam \
O=${Dog_ID}_alignment.metrics.txt

picard CollectInsertSizeMetrics \
I=${Dog_ID}.alignment.sort.dedup.bam \
O=${Dog_ID}_alignment_insert_size_metrics.txt \
H=${Dog_ID}_alignment_insert_size_histogram.pdf 



