#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
#You can edit the script since this line
#
# Your job name
#$ -N Bam_sam_d_ep_trim
#$ -t 1-4
#$ -l vf=10G
# Send an email after the job has finished
#$ -m e
#$ -o /mnt/Timina/cgonzaga/sgamino/Dog_epilepsy_alignment/logs/
#$ -e /mnt/Timina/cgonzaga/sgamino/Dog_epilepsy_alignment/logs/
#$ -M ghobibohg@gmail.com
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load htslib/1.2.1 
module load gcc/5.1.0
module load samtools/1.9
#
# Write your commands in the next line

#Aquí elijo todos los archivos a procesar en una lista
FILES=( /mnt/Timina/cgonzaga/sgamino/Dog_epilepsy_alignment/output/sam_output/*_trim_alignment.sam.gz )
#Aquí asigno una tarea a cada elemento de la lista
FILE=${FILES[$SGE_TASK_ID-1]}
#Por ultimo, tomo el nombre que va antes de la secuencia del nombre compartido 
BASE=$(basename "$FILE" _trim_alignment.sam.gz)

echo "Procesando tarea $FILE en tarea $SGE_TASK_ID"

#Ahora se corre el comando para transfromar los sam en bam, y seguir con el pileline.
samtools view -b -h "$FILE" -o "/mnt/Timina/cgonzaga/sgamino/Dog_epilepsy_alignment/output/bam_output/${BASE}.alignment.bam" 
