#!/bin/bash

#SBATCH --job-name=Dog_ann_database_creation_canFam4
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --output=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/logs/Dog_ann_database_creation_ncbi.out
#SBATCH --error=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/logs/Dog_ann_database_creation_ncbi.err
#SBATCH --chdir=/mnt/data/cgonzaga/sgamino/Dog_epilepsy_project/resources/annovar_dog/canFam4

module purge

# Carga tus modulos en la siguiente linea

module load htslib/1.16

# Your script goes here
#/home/sgamino/annovar/annotate_variation.pl -downdb -buildver canFam4 gene dog_ann_db 
#/home/sgamino/annovar/annotate_variation.pl --buildver canFam4 --downdb seq dog_ann_db/canFam4_seq
#wget --timestamping 'ftp://hgdownload.soe.ucsc.edu/goldenPath/canFam4/database/ncbiRefSeq.txt.gz'
#gunzip ncbiRefSeq.txt.gz
#mv ncbiRefSeq.txt canFam4_refGene.txt
#wget --timestamping 'ftp://hgdownload.soe.ucsc.edu/goldenPath/canFam4/database/ncbiRefSeqLink.txt.gz'
#gunzip ncbiRefSeqLink.txt.gz
#mv ncbiRefSeqLink.txt canFam4_ncbiRefSeqLink.txt
/home/sgamino/annovar/retrieve_seq_from_fasta.pl dog_ann_db/canFam4_refGene.txt -seqfile dog_ann_db/canFam4_seq/canFam4.fa -format refGene -outfile dog_ann_db/canFam4_ncbi_refGeneMrna.fa
